2023-07-01 19:29:00,395 - server.logger_ser -  INFO - app.__handle_request():51 - Success!
2023-07-01 19:29:00,395 - server.logger_ser - ERROR - app.__handle_request():61 - Can not save image file in request
Traceback (most recent call last):
  File "/home/thanh/workspace/api-server/server/app.py", line 53, in __handle_request
    img = Image.open(result["img_source"])
KeyError: 'img_source'
