2023-06-29 22:13:18,059 - logger_ser - ERROR - app.ocr_type_document():76 - Id not found!
2023-06-29 22:13:18,059 - logger_ser - ERROR - app.ocr_type_document():86 - 
Traceback (most recent call last):
  File "/media/HDD1/hai/api-server-template/server/app.py", line 77, in ocr_type_document
    raise Exception
Exception
2023-06-29 22:32:24,694 - logger_ser - ERROR - app.ocr_type_document():76 - Id not found!
2023-06-29 22:32:24,694 - logger_ser - ERROR - app.ocr_type_document():86 - 
Traceback (most recent call last):
  File "/media/HDD1/hai/api-server-template/server/app.py", line 77, in ocr_type_document
    raise Exception
Exception
2023-06-29 22:32:28,463 - logger_ser - ERROR - app.ocr_type_document():76 - Id not found!
2023-06-29 22:32:28,463 - logger_ser - ERROR - app.ocr_type_document():86 - 
Traceback (most recent call last):
  File "/media/HDD1/hai/api-server-template/server/app.py", line 77, in ocr_type_document
    raise Exception
Exception
2023-06-29 22:32:34,630 - logger_ser - ERROR - app.ocr_type_document():76 - Id not found!
2023-06-29 22:32:34,631 - logger_ser - ERROR - app.ocr_type_document():86 - 
Traceback (most recent call last):
  File "/media/HDD1/hai/api-server-template/server/app.py", line 77, in ocr_type_document
    raise Exception
Exception
2023-06-29 22:34:23,452 - logger_ser - ERROR - app.ocr_type_document():76 - Id not found!
2023-06-29 22:34:23,452 - logger_ser - ERROR - app.ocr_type_document():86 - 
Traceback (most recent call last):
  File "/media/HDD1/hai/api-server-template/server/app.py", line 77, in ocr_type_document
    raise Exception
Exception
2023-06-29 22:41:05,732 - logger_ser - ERROR - app.ocr_type_document():86 - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/media/HDD1/hai/api-server-template/server/app.py", line 78, in ocr_type_document
    _img_file = request.files["image"]
  File "/home/hai/miniconda3/envs/extractID/lib/python3.7/site-packages/werkzeug/datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2023-06-29 22:41:19,654 - logger_ser - ERROR - app.ocr_type_document():76 - Id not found!
2023-06-29 22:41:19,654 - logger_ser - ERROR - app.ocr_type_document():86 - 
Traceback (most recent call last):
  File "/media/HDD1/hai/api-server-template/server/app.py", line 77, in ocr_type_document
    raise Exception
Exception
