2023-06-29 23:30:27,535 - logger_ser - ERROR - app.upload_image():76 - Id not found!
2023-06-29 23:30:27,536 - logger_ser - ERROR - app.upload_image():87 - 
Traceback (most recent call last):
  File "/media/HDD1/hai/api-server-template/server/app.py", line 77, in upload_image
    raise Exception
Exception
2023-06-29 23:30:42,259 - logger_ser - ERROR - app.upload_image():76 - Id not found!
2023-06-29 23:30:42,259 - logger_ser - ERROR - app.upload_image():87 - 
Traceback (most recent call last):
  File "/media/HDD1/hai/api-server-template/server/app.py", line 77, in upload_image
    raise Exception
Exception
2023-06-29 23:32:00,226 - logger_ser - ERROR - app.upload_image():76 - Id not found!
2023-06-29 23:32:00,226 - logger_ser - ERROR - app.upload_image():87 - 
Traceback (most recent call last):
  File "/media/HDD1/hai/api-server-template/server/app.py", line 77, in upload_image
    raise Exception
Exception
