2023-06-29 23:45:17,950 - logger_ser - ERROR - app.upload():76 - Id not found!
2023-06-29 23:45:17,950 - logger_ser - ERROR - app.upload():86 - 
Traceback (most recent call last):
  File "/media/HDD1/hai/api-server-template/server/app.py", line 77, in upload
    raise Exception
Exception
2023-06-29 23:45:21,134 - logger_ser - ERROR - app.upload():76 - Id not found!
2023-06-29 23:45:21,135 - logger_ser - ERROR - app.upload():86 - 
Traceback (most recent call last):
  File "/media/HDD1/hai/api-server-template/server/app.py", line 77, in upload
    raise Exception
Exception
2023-06-29 23:45:44,342 - logger_ser - ERROR - app.upload():76 - Id not found!
2023-06-29 23:45:44,343 - logger_ser - ERROR - app.upload():86 - 
Traceback (most recent call last):
  File "/media/HDD1/hai/api-server-template/server/app.py", line 77, in upload
    raise Exception
Exception
2023-06-29 23:45:56,073 - logger_ser - ERROR - app.upload():76 - Id not found!
2023-06-29 23:45:56,073 - logger_ser - ERROR - app.upload():86 - 
Traceback (most recent call last):
  File "/media/HDD1/hai/api-server-template/server/app.py", line 77, in upload
    raise Exception
Exception
